Name: Service Loadbalancer
Description: The loadbalancer service
Author: jan gehring <jan.gehring@gmail.com>
License: Apache 2.0
Require:
  HAProxy:
    git: https://github.com/RexOps/rex-haproxy.git
    branch: master
  Keepalived:
    git: https://github.com/RexOps/rex-keepalived.git
    branch: master
